version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Europe/London
  open-pull-requests-limit: 99
